### ISSUE TITLE
Get the 50 Reefs Data

### ISSUE THREAD

**Issue by curran** [room302studio/wcs-coral-reef#4]
Maybe scrape out of here? 

https://www.50reefs.org/map

Maybe get from another inside source.

**Comment by curran** [comment]
I can isolate just the embedded map with the data

https://www.google.com/maps/d/embed?mid=1tRvdBSNOeqNIbdqDCsWK16jQRIazFIkC&ll=0.11633498738966491%2C0&z=2

**Comment by ejfox** [comment]
🚀
